/**
 * Founder 1,000-org source sector → canonical JID sector (36 main labels).
 * FOUNDER_DECISION_TAX_003_RESOLVED: holding/conglomerate labels are organization
 * structure, not operating sectors — they route to review, not a synthetic sector.
 */
export const FOUNDER_SOURCE_SECTOR_TO_SLUG: Readonly<Record<string, string>> = {
  'الخدمات المالية': 'finance-banking',
  'السياحة والضيافة والثقافة': 'tourism-hospitality',
  'الرعاية الصحية وعلوم الحياة': 'healthcare',
  'التقنية والاقتصاد الرقمي': 'technology-information',
  'الخدمات اللوجستية والنقل': 'transport-logistics',
  'الخدمات المهنية والاستشارية': 'professional-services',
  'التعدين والمعادن والمواد': 'mining',
  'الترفيه والرياضة والإعلام': 'entertainment-media',
  'العقار والتطوير الحضري': 'construction-real-estate',
  'القطاع الحكومي والعام': 'government-services',
  'الدفاع والطيران والفضاء': 'defense-security',
  'الطاقة والمرافق والمياه': 'water-utilities',
  'النفط والغاز والبتروكيماويات': 'energy-oil',
  'التشييد والهندسة والبنية التحتية': 'construction-real-estate',
  'التعليم وتنمية رأس المال البشري': 'education',
  'الصناعة والتصنيع': 'manufacturing',
  'التجزئة والتجارة الإلكترونية والخدمات الاستهلاكية': 'retail-ecommerce',
  'الغذاء والزراعة والاستزراع المائي': 'agriculture-food-security',
  'السيارات والنقل': 'automotive',
  'السيارات والتنقل': 'automotive',
  'التأمين وإدارة المخاطر': 'insurance',
  'إدارة المرافق والتشغيل': 'professional-services',
  'البيئة والاستدامة': 'environment-sustainability',
  'الفعاليات وسياحة الأعمال': 'tourism-hospitality',
  'التقنية والاتصالات': 'telecommunications',
  'التقنية المالية والخدمات المالية': 'fintech',
  'التصنيع والصناعة': 'manufacturing',
  'الدفاع والطيران': 'defense-security',
  'الطاقة والمياه والاستدامة': 'renewable-energy',
  'المقاولات والبنية التحتية': 'construction-real-estate',
  'السياحة والضيافة والترفيه': 'tourism-hospitality',
  'الإعلام والصناعات الإبداعية': 'entertainment-media',
  'الأغذية والزراعة': 'agriculture-food-security',
  'الصحة وعلوم الحياة': 'healthcare',
  'التعليم وتنمية القدرات': 'education',
  'الرياضة وجودة الحياة': 'sports',
}

/** Organization-structure labels — not operating-sector taxonomy (TAX_003). */
export const ORGANIZATION_STRUCTURE_SOURCE_SECTORS = new Set<string>([
  'المجموعات الاستثمارية والقابضة المتنوعة',
  'Conglomerate',
  'مجموعة قابضة',
  'Holding Company',
  'شركة قابضة',
])

export const FOUNDER_SOURCE_SECTOR_REASONING: Readonly<Record<string, string>> = {
  'الخدمات المالية': 'Financial services map to Finance & Banking canonical sector.',
  'السياحة والضيافة والثقافة': 'Tourism/hospitality/culture collapse to Tourism & Hospitality.',
  'الرعاية الصحية وعلوم الحياة': 'Healthcare and life sciences map to Healthcare.',
  'التقنية والاقتصاد الرقمي': 'Digital economy maps to Technology & Information.',
  'الخدمات اللوجستية والنقل': 'Logistics and transport map to Transport & Logistics.',
  'الخدمات المهنية والاستشارية': 'Professional/consulting services map to Professional Services.',
  'التعدين والمعادن والمواد': 'Mining and materials map to Mining.',
  'الترفيه والرياضة والإعلام': 'Entertainment/sports/media map to Entertainment & Media.',
  'العقار والتطوير الحضري': 'Urban real-estate development maps to Construction & Real Estate.',
  'القطاع الحكومي والعام': 'Government/general public sector maps to Government Services.',
  'الدفاع والطيران والفضاء': 'Defense/aviation/space map to Defense & Security (primary).',
  'الطاقة والمرافق والمياه': 'Utilities/water map to Water & Utilities.',
  'النفط والغاز والبتروكيماويات': 'Oil/gas/petrochemicals map to Energy & Oil.',
  'التشييد والهندسة والبنية التحتية': 'Construction/engineering/infrastructure map to Construction & Real Estate.',
  'التعليم وتنمية رأس المال البشري': 'Education and human capital map to Education.',
  'الصناعة والتصنيع': 'Industry/manufacturing map to Manufacturing.',
  'التجزئة والتجارة الإلكترونية والخدمات الاستهلاكية': 'Retail/e-commerce maps to Retail & E-Commerce.',
  'الغذاء والزراعة والاستزراع المائي': 'Food/agriculture/aquaculture map to Agriculture & Food Security.',
  'السيارات والنقل': 'Automotive maps to Automotive.',
  'السيارات والتنقل': 'Automotive/transport synonym maps to Automotive.',
  'التأمين وإدارة المخاطر': 'Insurance maps to Insurance.',
  'المجموعات الاستثمارية والقابضة المتنوعة':
    'TAX_003: holding/diversified group is organization structure — sector unresolved pending operating evidence.',
  'إدارة المرافق والتشغيل': 'Facilities/operations management maps to Professional Services.',
  'البيئة والاستدامة': 'Environment/sustainability maps to Environment & Sustainability.',
  'الفعاليات وسياحة الأعمال': 'Events/business tourism map to Tourism & Hospitality.',
  'التقنية والاتصالات': 'Technology/telecom maps to Telecommunications.',
  'التقنية المالية والخدمات المالية': 'Fintech maps to Fintech.',
  'التصنيع والصناعة': 'Manufacturing synonym maps to Manufacturing.',
  'الدفاع والطيران': 'Defense/aviation maps to Defense & Security.',
  'الطاقة والمياه والاستدامة': 'Energy/water/sustainability maps to Renewable Energy.',
  'المقاولات والبنية التحتية': 'Contracting/infrastructure maps to Construction & Real Estate.',
  'السياحة والضيافة والترفيه': 'Tourism/hospitality/entertainment maps to Tourism & Hospitality.',
  'الإعلام والصناعات الإبداعية': 'Media/creative industries map to Entertainment & Media.',
  'الأغذية والزراعة': 'Food/agriculture maps to Agriculture & Food Security.',
  'الصحة وعلوم الحياة': 'Health/life sciences synonym maps to Healthcare.',
  'التعليم وتنمية القدرات': 'Education/talent development maps to Education.',
  'الرياضة وجودة الحياة': 'Sports/wellbeing maps to Sports.',
}
