import type { ResearchOpportunityInput } from './types'

export const RESEARCH_CHECKED_AT = '2026-08-23T03:45:00+03:00'
export const RESEARCH_NOW = new Date('2026-08-23T03:45:00+03:00')

const ARAMCO_HOSTS = ['aramco.com', 'careers.aramco.com'] as const
const KAUST_CAREERS_HOSTS = ['kaust.edu.sa', 'careers.kaust.edu.sa'] as const
const KAUST_ADMISSIONS_HOSTS = ['kaust.edu.sa', 'admissions.kaust.edu.sa', 'apply.kaust.edu.sa'] as const
const ELM_HOSTS = ['elm.sa', 'career.elm.sa'] as const
const ACWA_HOSTS = ['acwapower.com', 'careers.acwapower.com'] as const
const HRDF_HOSTS = ['hrdf.org.sa', 'www.hrdf.org.sa'] as const

function aramcoTrack(input: {
  key: string
  stableId: string
  title: string
  titleAr: string
  url: string
  experience: string
  qualification: string
  specializations: string | null
  eligibility: string
  summaryAr: string
  summaryEn: string
  applyCtaPresent: boolean
  evidenceNote: string
}): ResearchOpportunityInput {
  return {
    source_record_key: input.key,
    source_stable_id: input.stableId,
    raw_title: input.title,
    title_ar: input.titleAr,
    title_en: input.title,
    raw_organization_name: 'Saudi Aramco',
    opportunity_type: 'job',
    source_url: input.url,
    apply_url: input.url,
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: ARAMCO_HOSTS,
    allowed_apply_hosts: ARAMCO_HOSTS,
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'energy-oil',
    qualification: input.qualification,
    specializations: input.specializations,
    eligibility: input.eligibility,
    experience_requirement: input.experience,
    work_mode: null,
    opens_at: null,
    deadline_at: '2026-12-31T00:00:00+03:00',
    deadline_precision: 'date_only',
    source_published_at: null,
    apply_cta_present: input.applyCtaPresent,
    filled_or_closed_banner: false,
    evidence_note: input.evidenceNote,
    short_summary_ar: input.summaryAr,
    short_summary_en: input.summaryEn,
    checked_at: RESEARCH_CHECKED_AT,
  }
}

export const RESEARCH_INVENTORY: readonly ResearchOpportunityInput[] = [
  aramcoTrack({
    key: 'aramco-engineering-graduates-1344',
    stableId: 'aramco:job-req:1344',
    title: 'Engineering Graduates (less than three years of work experience)',
    titleAr: 'خريجو الهندسة (أقل من ثلاث سنوات خبرة)',
    url: 'https://careers.aramco.com/saudi/job/Engineering-Graduates-(less-than-three-years-of-work-experience)/766636323/',
    experience: 'No prior work experience is required. Less than three years of work experience.',
    qualification: 'Bachelor’s degree or higher obtained through full-time study.',
    specializations:
      'Petroleum, Chemical, Mechanical, Electrical, Civil, Industrial, Marine, Aviation, Safety, Fire Protection Engineering and other engineering related disciplines.',
    eligibility: 'Saudi applicant track on the official Aramco careers portal. Minimum GPA for technical majors is 2.0/4 or 3.0/5 or equivalent.',
    summaryAr:
      'أرامكو السعودية تعلن عن مسار خريجي الهندسة للتقديم داخل المملكة. الفرصة موجهة إلى حاملي البكالوريوس أو أعلى في تخصصات هندسية محددة، دون اشتراط خبرة سابقة. آخر موعد للتقديم 31 ديسمبر 2026.',
    summaryEn:
      'Saudi Aramco lists an engineering-graduate hiring track for Saudi applicants. The source requires a full-time bachelor’s degree or higher in named engineering disciplines and states no prior work experience is required. Application closing date 31 December 2026.',
    applyCtaPresent: true,
    evidenceNote:
      'Official careers.aramco.com Saudi job detail Job Req ID 1344 showed Apply now and Job Offer Closing Date 31 December 2026 during the 2026-08-23 research run. Job location is stated as within Saudi Arabia, to be specified in the job offer.',
  }),
  aramcoTrack({
    key: 'aramco-computing-it-graduates-1408',
    stableId: 'aramco:job-req:1408',
    title: 'Computing and IT Graduates (less than three years of work experience)',
    titleAr: 'خريجو الحوسبة وتقنية المعلومات (أقل من ثلاث سنوات خبرة)',
    url: 'https://careers.aramco.com/saudi/job/Computing-and-IT-Graduates-(less-than-three-years-of-work-experience)/766636523/',
    experience: 'No prior work experience is required. Less than three years of work experience.',
    qualification: 'Bachelor’s degree or higher obtained through full-time study.',
    specializations:
      'Computer Engineering, Software Engineering, Network Engineering, Computer Science, Information Technology, Information Security and other computer related disciplines.',
    eligibility: 'Saudi applicant track. Minimum GPA for technical majors is 2.0/4 or 3.0/5 or equivalent.',
    summaryAr:
      'أرامكو السعودية تعلن عن مسار خريجي الحوسبة وتقنية المعلومات. الفرصة موجهة إلى حاملي البكالوريوس أو أعلى في تخصصات حاسوبية محددة، دون اشتراط خبرة سابقة. آخر موعد للتقديم 31 ديسمبر 2026.',
    summaryEn:
      'Saudi Aramco lists a computing and IT graduate hiring track on its official Saudi careers portal. The source names eligible computing majors, requires a full-time bachelor’s degree or higher, and states no prior work experience is required. Closing date 31 December 2026.',
    applyCtaPresent: true,
    evidenceNote:
      'Official careers.aramco.com Saudi job detail Job Req ID 1408 showed Apply now and Job Offer Closing Date 31 December 2026 during the 2026-08-23 research run.',
  }),
  aramcoTrack({
    key: 'aramco-other-graduates-1412',
    stableId: 'aramco:job-req:1412',
    title: 'Other Graduates (less than three years of work experience)',
    titleAr: 'خريجون آخرون (أقل من ثلاث سنوات خبرة)',
    url: 'https://careers.aramco.com/saudi/job/Other-Graduates-(less-than-three-years-of-work-experience)/766636923/',
    experience: 'No prior work experience is required. Less than three years of work experience.',
    qualification: 'Bachelor’s degree or higher obtained through full-time study for majors outside engineering, business and IT.',
    specializations: null,
    eligibility:
      'Saudi applicant track. Minimum GPA for technical majors is 2.0/4 or 3.0/5; for administrative majors 2.5/4 or 3.5/5 or equivalent.',
    summaryAr:
      'أرامكو السعودية تعلن عن مسار خريجين لتخصصات خارج الهندسة والأعمال وتقنية المعلومات. الفرصة تشترط بكالوريوس أو أعلى بنظام دوام كامل، دون اشتراط خبرة سابقة. آخر موعد للتقديم 31 ديسمبر 2026.',
    summaryEn:
      'Saudi Aramco lists an other-graduates hiring track for majors outside engineering, business, and IT. The source requires a full-time bachelor’s degree or higher and states no prior work experience is required. Closing date 31 December 2026.',
    applyCtaPresent: true,
    evidenceNote:
      'Official careers.aramco.com Saudi job detail Job Req ID 1412 showed Apply now and Job Offer Closing Date 31 December 2026 during the 2026-08-23 research run.',
  }),
  aramcoTrack({
    key: 'aramco-business-graduates-1358',
    stableId: 'aramco:job-req:1358',
    title: 'Business Graduates (less than three years of work experience)',
    titleAr: 'خريجو الأعمال (أقل من ثلاث سنوات خبرة)',
    url: 'https://careers.aramco.com/saudi/job/Business-Graduates-%28less-than-three-years-of-work-experience%29/766636423/',
    experience: 'No prior work experience is required. Less than three years of work experience.',
    qualification: 'Bachelor’s degree or higher obtained through full-time study.',
    specializations:
      'Management Information Systems, Business Administration, Finance, Accounting, Marketing, Supply Chain Management, Project Management, Human Resources, Economics and other business-related disciplines.',
    eligibility: 'Saudi applicant track. Minimum GPA for administrative majors is 2.5/4 or 3.5/5 or equivalent.',
    summaryAr:
      'أرامكو السعودية تعلن عن مسار خريجي الأعمال. الفرصة موجهة إلى حاملي البكالوريوس أو أعلى في تخصصات أعمال محددة، دون اشتراط خبرة سابقة. آخر موعد للتقديم 31 ديسمبر 2026.',
    summaryEn:
      'Saudi Aramco lists a business-graduate hiring track on its official Saudi careers portal. The source names eligible business majors and states no prior work experience is required. Closing date 31 December 2026.',
    applyCtaPresent: true,
    evidenceNote:
      'Official careers.aramco.com Saudi listing and job detail Job Req ID 1358 were current on 2026-08-23 with Job Offer Closing Date 31 December 2026. The posting remains on the For Saudi Applicants list.',
  }),
  aramcoTrack({
    key: 'aramco-experienced-it-16741',
    stableId: 'aramco:job-req:16741',
    title: 'Experienced IT (more than three years of work experience)',
    titleAr: 'تقنية معلومات ذوو خبرة (أكثر من ثلاث سنوات)',
    url: 'https://careers.aramco.com/saudi/job/Experienced-IT-%28more-than-three-years-of-work-experience%29/856956923/',
    experience: 'Minimum of three years of work experience.',
    qualification: 'Bachelor\'s degree or higher obtained through full-time study. Diploma or high school degree obtained through full-time study is also listed.',
    specializations: 'Information Technology.',
    eligibility: 'Saudi applicant experienced track.',
    summaryAr:
      'أرامكو السعودية تعلن عن مسار تقنية معلومات للذوي الخبرة. المصدر يشترط ثلاث سنوات خبرة على الأقل. آخر موعد للتقديم 31 ديسمبر 2026.',
    summaryEn:
      'Saudi Aramco lists an experienced IT hiring track requiring at least three years of work experience. Closing date 31 December 2026.',
    applyCtaPresent: true,
    evidenceNote:
      'Official careers.aramco.com Saudi job detail Job Req ID 16741 showed Apply now and Job Offer Closing Date 31 December 2026 during the 2026-08-23 research run.',
  }),
  aramcoTrack({
    key: 'aramco-experienced-engineer-16740',
    stableId: 'aramco:job-req:16740',
    title: 'Experienced Engineer (more than three years of work experience)',
    titleAr: 'مهندسون ذوو خبرة (أكثر من ثلاث سنوات)',
    url: 'https://careers.aramco.com/saudi/job/Experienced-Engineer-%28more-than-three-years-of-work-experience%29/856956723/',
    experience: 'Minimum of three years of work experience.',
    qualification: 'Bachelor\'s degree or higher obtained through full-time study. Diploma or high school degree obtained through full-time study is also listed.',
    specializations: 'Recognized engineering fields.',
    eligibility: 'Saudi applicant experienced track.',
    summaryAr:
      'أرامكو السعودية تعلن عن مسار هندسي للذوي الخبرة. المصدر يشترط ثلاث سنوات خبرة على الأقل. آخر موعد للتقديم 31 ديسمبر 2026.',
    summaryEn:
      'Saudi Aramco lists an experienced engineer hiring track requiring at least three years of work experience. Closing date 31 December 2026.',
    applyCtaPresent: true,
    evidenceNote:
      'Official careers.aramco.com Saudi listing and job detail Job Req ID 16740 were current on 2026-08-23 with Job Offer Closing Date 31 December 2026.',
  }),
  {
    source_record_key: 'kaust-integration-architect-developer-expert-1423404933',
    source_stable_id: 'kaust:job:1423404933',
    raw_title: 'Integration Architect/Developer Expert',
    title_ar: 'خبير هندسة وتطوير التكامل',
    title_en: 'Integration Architect/Developer Expert',
    raw_organization_name: 'King Abdullah University of Science and Technology',
    opportunity_type: 'job',
    source_url: 'https://careers.kaust.edu.sa/job/Integration-ArchitectDeveloper-Expert/1423404933/',
    apply_url: 'https://careers.kaust.edu.sa/job/Integration-ArchitectDeveloper-Expert/1423404933/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: KAUST_CAREERS_HOSTS,
    allowed_apply_hosts: KAUST_CAREERS_HOSTS,
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'education',
    qualification:
      'Bachelor\'s degree in Computer Science, Software Engineering, Information Technology, Engineering or a related discipline, or an equivalent combination of education and substantial relevant experience.',
    specializations: 'Enterprise integration, API management, cloud and hybrid integration.',
    eligibility: null,
    experience_requirement: 'Source describes a senior technical leadership role; no numeric years stated as a hard minimum.',
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: '2026-08-05T00:00:00+03:00',
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official careers.kaust.edu.sa job page dated 5 August 2026 showed Apply now and no filled banner during the 2026-08-23 research run. Location stated as Saudi Arabia. No application deadline was stated.',
    short_summary_ar:
      'جامعة الملك عبدالله للعلوم والتقنية تعلن عن وظيفة Integration Architect/Developer Expert في المملكة العربية السعودية. المصدر يعرض زر التقديم دون موعد ختامي معلن.',
    short_summary_en:
      'KAUST lists an Integration Architect/Developer Expert role in Saudi Arabia on its official careers portal. The page showed Apply now on 23 August 2026 and did not state a deadline.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'kaust-research-user-computing-lead-1425615433',
    source_stable_id: 'kaust:job:1425615433',
    raw_title: 'Research User Computing Lead',
    title_ar: 'رئيس حوسبة مستخدمي البحث',
    title_en: 'Research User Computing Lead',
    raw_organization_name: 'King Abdullah University of Science and Technology',
    opportunity_type: 'job',
    source_url: 'https://careers.kaust.edu.sa/job/Research-User-Computing-Lead/1425615433/',
    apply_url: 'https://careers.kaust.edu.sa/job/Research-User-Computing-Lead/1425615433/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: KAUST_CAREERS_HOSTS,
    allowed_apply_hosts: KAUST_CAREERS_HOSTS,
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'education',
    qualification: null,
    specializations: 'Linux scientific workstation platforms; supervision of Windows and macOS engineers is also described.',
    eligibility: null,
    experience_requirement: null,
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: '2026-08-12T00:00:00+03:00',
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official careers.kaust.edu.sa job page dated 12 August 2026 showed Apply now and no filled banner during the 2026-08-23 research run. Location stated as Saudi Arabia. No application deadline was stated.',
    short_summary_ar:
      'جامعة الملك عبدالله للعلوم والتقنية تعلن عن وظيفة Research User Computing Lead في المملكة العربية السعودية. المصدر يعرض زر التقديم دون موعد ختامي معلن.',
    short_summary_en:
      'KAUST lists a Research User Computing Lead role in Saudi Arabia. The official page showed Apply now on 23 August 2026 and did not state a deadline.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'kaust-senior-financial-analyst-treasury-1426843033',
    source_stable_id: 'kaust:job:1426843033',
    raw_title: 'Senior Financial Analyst - Treasury and Collection',
    title_ar: 'محلل مالي أول — الخزينة والتحصيل',
    title_en: 'Senior Financial Analyst - Treasury and Collection',
    raw_organization_name: 'King Abdullah University of Science and Technology',
    opportunity_type: 'job',
    source_url: 'https://careers.kaust.edu.sa/job/Senior-Financial-Analyst-Treasury-and-Collection/1426843033/',
    apply_url: 'https://careers.kaust.edu.sa/job/Senior-Financial-Analyst-Treasury-and-Collection/1426843033/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: KAUST_CAREERS_HOSTS,
    allowed_apply_hosts: KAUST_CAREERS_HOSTS,
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'education',
    qualification: 'Bachelor’s degree in Accounting, Finance or other related major.',
    specializations: 'Treasury and collection; SAP or ERP experience is described as highly desirable.',
    eligibility: null,
    experience_requirement: 'Minimum 5 years of experience in same role in a complex environment.',
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: '2026-08-17T00:00:00+03:00',
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official careers.kaust.edu.sa job page dated 17 August 2026 returned the full job description during the 2026-08-23 research run with no filled banner. Location stated as Saudi Arabia. No application deadline was stated.',
    short_summary_ar:
      'جامعة الملك عبدالله للعلوم والتقنية تعلن عن وظيفة محلل مالي أول في الخزينة والتحصيل. المصدر يشترط بكالوريوس محاسبة أو مالية أو تخصص ذي صلة، وخمس سنوات خبرة في الدور نفسه. لا يوجد موعد ختامي معلن.',
    short_summary_en:
      'KAUST lists a Senior Financial Analyst – Treasury and Collection role. The source requires a bachelor’s degree in accounting, finance or a related major and a minimum of five years in the same role. No deadline was stated.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'kaust-vsrp-internship-program',
    source_stable_id: 'kaust:program:vsrp',
    raw_title: 'Visiting Student Research Program (VSRP)',
    title_ar: 'برنامج الطالب الزائر البحثي',
    title_en: 'Visiting Student Research Program (VSRP)',
    raw_organization_name: 'King Abdullah University of Science and Technology',
    opportunity_type: 'internship',
    source_url: 'https://admissions.kaust.edu.sa/study/internships',
    apply_url: 'https://apply.kaust.edu.sa/portal/vsrp',
    source_type: 'official_university_program',
    source_tier: 'A',
    official_source_hosts: KAUST_ADMISSIONS_HOSTS,
    allowed_apply_hosts: KAUST_ADMISSIONS_HOSTS,
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'research-development',
    qualification: 'Undergraduate students in 3rd year or above and master’s students. Minimum GPA 3.5/4.0 or equivalent.',
    specializations: 'STEM faculty-led research projects.',
    eligibility:
      'Current PhD candidates, KAUST students or KAUST alumni are not eligible. English proficiency evidence is required unless a listed exemption applies.',
    experience_requirement: null,
    work_mode: 'onsite',
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: null,
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official KAUST admissions internships page states application deadlines are all year round and directs applicants to apply via the project/VSRP portal. Page was opened on 2026-08-23. This is recorded as one program-level internship, not as invented individual projects.',
    short_summary_ar:
      'جامعة الملك عبدالله للعلوم والتقنية تعلن عن برنامج تدريب بحثي للطلاب الزائرين على مدار السنة. الفرصة موجهة إلى طلاب البكالوريوس من السنة الثالثة فأعلى وطلاب الماجستير في تخصصات العلوم والتقنية، بمعدل لا يقل عن 3.5 من 4.',
    short_summary_en:
      'KAUST’s official admissions page describes the Visiting Student Research Program as open year-round. Eligible applicants are third-year or above undergraduates and master’s students with a minimum GPA of 3.5/4.0.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'elm-associate-principal-ai-platform-654012',
    source_stable_id: 'elm:job:654012',
    raw_title: 'Associate Principal - AI Platform',
    title_ar: 'رئيس مشارك — منصة الذكاء الاصطناعي',
    title_en: 'Associate Principal - AI Platform',
    raw_organization_name: 'Elm',
    opportunity_type: 'job',
    source_url: 'https://career.elm.sa/elm/job/Riyadh-Associate-Principal-AI-Platform-Job/1368992457/',
    apply_url: 'https://career.elm.sa/elm/job/Riyadh-Associate-Principal-AI-Platform-Job/1368992457/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: ELM_HOSTS,
    allowed_apply_hosts: ELM_HOSTS,
    location_country: 'SA',
    location_region: 'riyadh',
    location_city: 'Riyadh',
    sector_slug: 'artificial-intelligence',
    qualification:
      'Bachelor\'s degree in Computer Science, Information Systems, Software Engineering, Artificial Intelligence, Business Analysis, or a related field. Master\'s degree is preferred.',
    specializations: 'AI platforms, business analysis, product management, digital solutions.',
    eligibility: null,
    experience_requirement:
      '6–8 years of experience in AI platforms, business analysis, product management, digital solutions, or AI-enabled technology initiatives.',
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: '2026-08-09T00:00:00+03:00',
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official career.elm.sa job page dated 9 August 2026 showed Apply now and no filled banner during the 2026-08-23 research run. Location Riyadh. Job code 654012.',
    short_summary_ar:
      'شركة علم تعلن عن وظيفة Associate Principal في منصة الذكاء الاصطناعي بالرياض. المصدر يشترط بكالوريوس في تخصص تقني ذي صلة وخبرة من 6 إلى 8 سنوات. لا يوجد موعد ختامي معلن.',
    short_summary_en:
      'Elm lists an Associate Principal – AI Platform role in Riyadh. The source requires a relevant bachelor’s degree and 6–8 years of experience. No deadline was stated.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'elm-consultant-portfolio-integrations-679071',
    source_stable_id: 'elm:job:679071',
    raw_title: 'Consultant',
    title_ar: 'مستشار',
    title_en: 'Consultant',
    raw_organization_name: 'Elm',
    opportunity_type: 'job',
    source_url: 'https://career.elm.sa/elm/job/Riyadh-Consultant-Job/1369654657/',
    apply_url: 'https://career.elm.sa/elm/job/Riyadh-Consultant-Job/1369654657/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: ELM_HOSTS,
    allowed_apply_hosts: ELM_HOSTS,
    location_country: 'SA',
    location_region: 'riyadh',
    location_city: 'Riyadh',
    sector_slug: 'professional-services',
    qualification:
      'Bachelor’s degree in Business Administration, Finance, Economics, Industrial Engineering, or a related field.',
    specializations: 'Corporate development, post-merger integration, value creation.',
    eligibility: null,
    experience_requirement:
      '4–6 years of experience in corporate development, post-merger integration, strategy, transaction advisory, value creation, or related fields.',
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: '2026-08-17T00:00:00+03:00',
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official career.elm.sa job page dated 17 August 2026 showed Apply now and no filled banner during the 2026-08-23 research run. Location Riyadh. Job code 679071. Department Portfolio & Integrations Management.',
    short_summary_ar:
      'شركة علم تعلن عن وظيفة مستشار في الرياض ضمن إدارة المحفظة والتكامل. المصدر يشترط بكالوريوس في إدارة الأعمال أو المالية أو الاقتصاد أو الهندسة الصناعية أو تخصص ذي صلة، وخبرة من 4 إلى 6 سنوات.',
    short_summary_en:
      'Elm lists a Consultant role in Riyadh in portfolio and integrations management. The source requires a relevant bachelor’s degree and 4–6 years of experience. No deadline was stated.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'acwa-planning-engineer-rabigh-857297623',
    source_stable_id: 'acwapower:job:857297623',
    raw_title: 'Planning Engineer',
    title_ar: 'مهندس تخطيط',
    title_en: 'Planning Engineer',
    raw_organization_name: 'ACWA Power',
    opportunity_type: 'job',
    source_url: 'https://careers.acwapower.com/job/Planning-Engineer/857297623/',
    apply_url: 'https://careers.acwapower.com/job/Planning-Engineer/857297623/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: ACWA_HOSTS,
    allowed_apply_hosts: ACWA_HOSTS,
    location_country: 'SA',
    location_region: 'makkah',
    location_city: 'Rabigh',
    sector_slug: 'energy-oil',
    qualification: 'Bachelor\'s degree in Mechanical, Electrical, or Instrumentation Engineering.',
    specializations: 'Maintenance planning and scheduling in power generation, utilities, or industrial plant environments.',
    eligibility: null,
    experience_requirement:
      'Minimum 8 years of experience in maintenance planning and scheduling within a power generation, utilities, or industrial plant environment. SAP PM experience is essential.',
    work_mode: 'onsite',
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: '2026-08-07T00:00:00+03:00',
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official careers.acwapower.com job page dated 7 August 2026 returned the full job description during the 2026-08-23 research run with no filled banner. Location stated as KSA/Rabigh. A different ACWA Field Operator posting on the same portal showed a filled banner and was excluded.',
    short_summary_ar:
      'أكوا باور تعلن عن وظيفة مهندس تخطيط في رابغ. المصدر يشترط بكالوريوس هندسة ميكانيكية أو كهربائية أو أجهزة، وثماني سنوات خبرة في تخطيط الصيانة، مع خبرة SAP PM. لا يوجد موعد ختامي معلن.',
    short_summary_en:
      'ACWA Power lists a Planning Engineer role in Rabigh, Saudi Arabia. The source requires a relevant engineering bachelor’s degree, eight years of maintenance-planning experience, and SAP PM. No deadline was stated.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'hrdf-tamheer-graduate-development',
    source_stable_id: 'hrdf:program:tamheer',
    raw_title: 'Graduate Development - Tamheer',
    title_ar: 'تطوير الخريجين — تمهير',
    title_en: 'Graduate Development - Tamheer',
    raw_organization_name: 'Human Resources Development Fund',
    opportunity_type: 'internship',
    source_url: 'https://www.hrdf.org.sa/en/products-and-services/programs/individuals/training/graduate-development/',
    apply_url: 'https://www.hrdf.org.sa/products-and-services/programs/individuals/training/graduate-development/apply/',
    source_type: 'official_government_portal',
    source_tier: 'A',
    official_source_hosts: HRDF_HOSTS,
    allowed_apply_hosts: HRDF_HOSTS,
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'vocational-training',
    qualification:
      'Diploma of at least one academic year from an accredited authority, or a bachelor’s degree or higher from a Saudi or Ministry of Education-accredited foreign university.',
    specializations: null,
    eligibility:
      'Saudi national. Must be registered on the HRDF website. Must not have fully used Tamheer credit beyond two opportunities totalling six months.',
    experience_requirement: null,
    work_mode: 'onsite',
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: null,
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note:
      'Official HRDF English and Arabic Tamheer pages describe current application steps through HRDF electronic services and Nafath, with no closed banner. English page last-update stamp observed as 2 February 2026. Recorded as one program-level internship, not as invented employer placements. Application itself requires login via Nafath; this research did not enter private applicant areas.',
    short_summary_ar:
      'صندوق تنمية الموارد البشرية يتيح التقديم على منتج تطوير الخريجين (تمهير) عبر خدماته الإلكترونية. الفرصة موجهة إلى السعوديين من حملة الدبلوم أو البكالوريوس فأعلى وفق الشروط المعلنة في المصدر الرسمي.',
    short_summary_en:
      'The Human Resources Development Fund publishes Tamheer as a graduate on-the-job training product with official application steps. Eligibility is limited to Saudi nationals meeting the stated diploma or bachelor’s requirements.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'stc-contract-management-expert-filled',
    source_stable_id: 'stc:job:857334423',
    raw_title: 'Contract Management Expert',
    title_ar: null,
    title_en: 'Contract Management Expert',
    raw_organization_name: 'stc',
    opportunity_type: 'job',
    source_url: 'https://careers.stc.com.sa/job/Contract-Management-Expert/857334423/',
    apply_url: 'https://careers.stc.com.sa/job/Contract-Management-Expert/857334423/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: ['stc.com.sa', 'careers.stc.com.sa'],
    allowed_apply_hosts: ['stc.com.sa', 'careers.stc.com.sa'],
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'telecommunications',
    qualification: null,
    specializations: null,
    eligibility: null,
    experience_requirement: '4-6 Years',
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: '2026-08-13T00:00:00+03:00',
    apply_cta_present: false,
    filled_or_closed_banner: true,
    evidence_note:
      'Official careers.stc.com.sa job page dated 13 August 2026 displayed: Sorry, this position has been filled.',
    short_summary_ar: 'صفحة stc الرسمية تعرض أن الوظيفة قد شغلت.',
    short_summary_en: 'The official stc job page states the position has been filled.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'sabic-sr-engineer-maintenance-planning-unavailable',
    source_stable_id: 'sabic:job:857196823',
    raw_title: 'Sr. Engineer, Maintenance Planning (J) - GAS',
    title_ar: null,
    title_en: 'Sr. Engineer, Maintenance Planning (J) - GAS',
    raw_organization_name: 'SABIC',
    opportunity_type: 'job',
    source_url: 'https://jobs.sabic.com/job/Jubail-Sr_-Engineer%2C-Maintenance-Planning-%28J%29-GAS/857196823/',
    apply_url: 'https://jobs.sabic.com/job/Jubail-Sr_-Engineer%2C-Maintenance-Planning-%28J%29-GAS/857196823/',
    source_type: 'career_page',
    source_tier: 'A',
    official_source_hosts: ['sabic.com', 'jobs.sabic.com'],
    allowed_apply_hosts: ['sabic.com', 'jobs.sabic.com'],
    location_country: 'SA',
    location_region: 'eastern-province',
    location_city: 'Jubail',
    sector_slug: 'chemicals',
    qualification: null,
    specializations: null,
    eligibility: null,
    experience_requirement: null,
    work_mode: null,
    opens_at: '2026-05-06T00:00:00+03:00',
    deadline_at: '2026-05-13T00:00:00+03:00',
    deadline_precision: 'date_only',
    source_published_at: '2026-05-06T00:00:00+03:00',
    apply_cta_present: false,
    filled_or_closed_banner: true,
    evidence_note:
      'Official jobs.sabic.com page redirected to a not-available state: You can\'t view this job because it\'s not available at this time. Search snippets also showed Job Post End Date 13 May 2026, which is before this research run.',
    short_summary_ar: 'صفحة سابك الرسمية تعرض أن الوظيفة غير متاحة حاليا.',
    short_summary_en: 'The official SABIC job page states the posting is not available at this time.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'pif-gdp-application-closed',
    source_stable_id: 'pif:program:gdp',
    raw_title: 'Graduate Development Program',
    title_ar: 'برنامج تطوير الخريجين',
    title_en: 'Graduate Development Program',
    raw_organization_name: 'Public Investment Fund',
    opportunity_type: 'job',
    source_url: 'https://www.pif.gov.sa/en/careers/graduate-development-program/',
    apply_url: 'https://www.pif.gov.sa/en/careers/graduate-development-program/',
    source_type: 'official_program',
    source_tier: 'A',
    official_source_hosts: ['pif.gov.sa', 'www.pif.gov.sa'],
    allowed_apply_hosts: ['pif.gov.sa', 'www.pif.gov.sa'],
    location_country: 'SA',
    location_region: 'riyadh',
    location_city: 'Riyadh',
    sector_slug: 'finance-investment',
    qualification: 'Bachelor\'s or Master\'s degree in listed disciplines.',
    specializations:
      'Business Administration, Finance and Accounting, Engineering, Law, Statistics, Risk Management, Applied and Financial Mathematics, Actuarial Science, Artificial Intelligence, Data Science, Information Technology, Cybersecurity, or Economics.',
    eligibility: 'Saudi national. Graduation year between 2024 and 2026. Minimum GPA 3.75/5 or 2.75/4.',
    experience_requirement: null,
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: null,
    apply_cta_present: false,
    filled_or_closed_banner: true,
    evidence_note:
      'Official PIF GDP page displayed: The application is now closed. FAQ language about a current edition was not treated as sufficient against the program page closed banner.',
    short_summary_ar: 'صفحة صندوق الاستثمارات العامة الرسمية تعرض أن التقديم على برنامج تطوير الخريجين مغلق حاليا.',
    short_summary_en: 'The official PIF Graduate Development Program page states the application is now closed.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'aramco-university-internship-2026-closed',
    source_stable_id: 'aramco:program:uip-2026',
    raw_title: 'University Internship Program',
    title_ar: 'برنامج التدريب الجامعي',
    title_en: 'University Internship Program',
    raw_organization_name: 'Saudi Aramco',
    opportunity_type: 'internship',
    source_url:
      'https://www.aramco.com/en/careers/for-saudi-applicants/student-opportunities/university-and-vocational-college-internship-programs/university-internship-program',
    apply_url:
      'https://www.aramco.com/en/careers/for-saudi-applicants/student-opportunities/university-and-vocational-college-internship-programs/university-internship-program',
    source_type: 'official_program',
    source_tier: 'A',
    official_source_hosts: ARAMCO_HOSTS,
    allowed_apply_hosts: ARAMCO_HOSTS,
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: 'energy-oil',
    qualification: null,
    specializations: null,
    eligibility: 'Saudi students required by their universities to undergo practical training prior to graduation.',
    experience_requirement: null,
    work_mode: 'onsite',
    opens_at: '2026-06-22T08:00:00+03:00',
    deadline_at: '2026-06-29T15:00:00+03:00',
    deadline_precision: 'timestamp',
    source_published_at: null,
    apply_cta_present: false,
    filled_or_closed_banner: true,
    evidence_note:
      'Official Aramco University Internship Program page states the application window was 08:00 on 22 June 2026 until 15:00 on 29 June 2026. That window is before this research run.',
    short_summary_ar: 'أرامكو السعودية تعلن أن فترة التسجيل في برنامج التدريب الجامعي لعام 2026 قد انتهت.',
    short_summary_en: 'Saudi Aramco’s official University Internship Program page states the 2026 registration window has ended.',
    checked_at: RESEARCH_CHECKED_AT,
  },
  {
    source_record_key: 'aggregator-lead-rejected-tier-c',
    source_stable_id: 'tier-c:example-aggregator',
    raw_title: 'Generic aggregator lead',
    title_ar: null,
    title_en: 'Generic aggregator lead',
    raw_organization_name: 'Unknown aggregator',
    opportunity_type: 'job',
    source_url: 'https://example-jobs-aggregator.test/saudi-aramco-jobs',
    apply_url: 'https://example-jobs-aggregator.test/saudi-aramco-jobs',
    source_type: 'career_page',
    source_tier: 'C',
    official_source_hosts: ['example-jobs-aggregator.test'],
    allowed_apply_hosts: ['example-jobs-aggregator.test'],
    location_country: 'SA',
    location_region: null,
    location_city: null,
    sector_slug: null,
    qualification: null,
    specializations: null,
    eligibility: null,
    experience_requirement: null,
    work_mode: null,
    opens_at: null,
    deadline_at: null,
    deadline_precision: 'absent',
    source_published_at: null,
    apply_cta_present: true,
    filled_or_closed_banner: false,
    evidence_note: 'Synthetic Tier C discovery-only lead used to prove publication exclusion. Not a live official source.',
    short_summary_ar: 'مصدر تجميعي غير رسمي. لا يُنشر.',
    short_summary_en: 'Non-authoritative aggregator lead. Not publishable.',
    checked_at: RESEARCH_CHECKED_AT,
  },
]
